[package]
name = "dimo-rust-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
serde_json = "1.0"
sha3 = "0.10"
reqwest = { version = "0.12", features = ["json"] }
secp256k1 = {version="0.29", features=["recovery"] }
serde = { version = "1.0", features = ["derive"] }